import type { Metadata } from 'next'
import { Inter, Rubik, Syne } from 'next/font/google'
import './globals.css'
import NavigationBar from '@/components/common/navbar'
import Footer from '@/components/common/footer'

const inter = Inter({ subsets: ['latin'] })
const rubik = Rubik({ subsets: ['latin'] })
const syne = Syne({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <NavigationBar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
